### ISSUE TITLE
[BUG] GraphqlBirdseye not in module

### ISSUE THREAD

**Issue by hansamann** [Novvum/graphql-birdseye#26]
**Describe the bug**
GraphqlBirdseye does not seem to be part of "graphql-birdseye-core"

**To Reproduce**
Generate a new vue app, yarn add the lib adn then add this to the script:

import * as bs from "graphql-birdseye-core";
console.log(bs);

Looking at the console output in the browser: no 'GraphqlBirdseye'

**Expected behavior**

GraphqlBirdseye available.

**Screenshots**

**Package**
graphql-birdseye-core

**Additional context**

**Comment by rohit-ravikoti** [comment]
@hansamann, thank you for submitting the issue. I will try to reproduce this and see what might be happening.

**Comment by Jorge0521** [comment]
@hansamann  I tried reproducing the bug in both React and Vue, but couldn't get the issue that you are facing. Here are the links to both sandboxes were graphql-birdseye-core works fine. If you have any other questions, feel free ask!

React: https://codesandbox.io/s/lingering-worker-0hobi
Vue: https://codesandbox.io/s/vue-template-3zsze

**Comment by rohit-ravikoti** [comment]
Closing this since there is no response.
