### ISSUE TITLE
[BUG] Fresh clone won't compile GitHub query

### ISSUE THREAD

**Issue by mattbishop** [Novvum/graphql-birdseye#30]
**Describe the bug**
I just cloned GraphQL-birdseye and ran `yarn install`, then hit the localhost:8000 page.

**To Reproduce**
1. Clone the repo
2. Run `yarn install` with yarn 1.16 and node 10
3. See a build error, but ignore.
4. Go to running Birdseye server at http://locahost:8000 and see error:

GraphQL Error Unknown type "GitHub_Blob".

  file: /Users/matt/Projects/graphql-birdseye/example/src/components/GetStarted.tsx

   1 | 
   2 |               {
   3 |                 github {
   4 |                   repository(owner: "Novvum", name: "graphql-birdseye") {
   5 |                     object(expression: "master:README.md") {
>  6 |                       ... on GitHub_Blob {
     |                              ^
   7 |                         text
   8 |                       }
   9 |                     }
  10 |                   }
  11 |                 }
  12 |               }
  13 |             
**Expected behavior**
I expect to see the example start up.

**Comment by rohit-ravikoti** [comment]
I think this is because Unions are currently not yet supported. I will be adding the functionality soon. Please stay posted!
